CXX = g++
CXXFLAGS = -O2 -std=c++17 -Wall -Wextra -Wconversion -Wno-unused-result -pedantic -Wshadow -Wformat=2 -Wfloat-equal -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align 
DEBUGFLAGS = -fsanitize=undefined -fsanitize=address -fno-sanitize-recover=all -fstack-protector -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2
CXXFLAGS += $(DEBUGFLAGS)
